Oct 3rd, 2022
Key word: "cannabis"   Database:SRA
9497 results Source = RNA

Sample picked:

GenBank: JAATIP010000026.1

Using the Open Reading Frame Finder: Input "JAATIP010000026.1"
Default settings: Minimal ORF length (nt):75
ORF start codon to use:
 "ATG" only

Contig: 
MGPQSGFAREQQETFTRKRENPFYKGLLKQNDQNFTFDFPKSSG
                     NHNVPRSISDIGHGKIETFDFYANETSMESSFEDSMTKSNFEPFNQATLEKSKKVSKT
                     TPNTFTRASSDLEFSFRSLQDSINELHGLTLKKYEDHQTLHGSSKPIEKTYPVNKRKE
                     DLSSIQLPQCAASFYNGISPIMEVVEQCETAKRLNLYLRAGKVEVNAGVPGRFLHAVI
                     AQDVSDVGSVALTIAYAFYLNETQKKKEYCTVPVINMKREELNARVDLSYYDLFGSLK
                     LVLLNGQKLPAKQEALKDATVEILTCRKGEPAYPSVEVVTETEFALTSPETLVGKGFS
                     RLLLAGILSDTENLTKPLCSSKDKYMASLLIHGAGRLGYNGLYQLLKYKKHDVSELKV
                     VDILRKDFKRWTRVGKQDTYGSRLSNNGLSSIGISIGQLLSHESAAPQQIKYFQQLEK
                     LRLLMIVSGYYDSNKNFKREILVSTESVVLMKTLLNFFNSNATLLPLKDLHRPGKPYG
                     GDESIRNR
                    
Contig: MDSSKNRAIPSLISHNQIHHFLLLILLFHFSTSFLSSTAQETAV
                     VGYGYKIKSIHSQYSGKLLTGNLQLIKNSSTYGPDIQSLTLTASYDTADRLRIRITDA
                     KKKRWEVPKDIIPGQTHTQSQLRFLPEIQFPAKPNSDLVLTFHNTTPFGFSVSRRSTG
                     ETIFDTSPVNSKPETRLVFKDQFLQISSSLPKDRSNLYGLGEQTRKSFRLRPNQTLTL
                     WNADIGSVNTDVNLYGSHPFYMDVRSPSGATHGVLLLNSNGMDIDYSGDRITYKMIGG
                     VIDLYFFAGPNPESVLDQYTELIGRPTPMPYWSFGFHQCRYGYKNVSDVEGVVAGYAA
                     AKIPLEVIWTDIDYMDAYKDFTLDPINFPVEKMKRFVDKVHQDGQKYVLIIDPGIGVN
                     KTYKTYLRGMEADVFIKRDGVPYLGEVWPGPVYFPDFLNPASYKYWRTEIKLFRDVLP
                     FDGIWLDMNEVSNFISSPPKPSSKLDNPPYKINNAFGRPIINKTLPATCLHYGNVTEY
                     NAHNLYGLYECKVTNAALVNVTGKRPFVLSRSTFVGSGKYTAHWTGDNAATWDDLAYT
                     IPSILNFGLFGIPMVGADICGFSGNTTEELCRRWIQLGAFYPFARDHSDKFTIRQELY
                     LWNSVAASARKVLGLRYRLLPTFYTLMYDAHKKGTPIARPLFFSFPKDTKTYNISSQF
                     LLGKGILVSPVLKAQTYSVNAYFPAGNWFDMFNYSSSVSVTSGQYVMLSAPADHINVH
                     VREGNILALQGEAMTTQAARKTAFNLLVISSMSTNSTGEVFLDDGEDVKMGEEGGKWS
                     LVSFSSSVGKDGVVIGSNISNGQFALTQKWIISKITLIGLEKAKKVKEYKLYSGGTLI
                     KDSSIKTSFYSFGKFSTVEMTGLPLLIGEEFKLVLTFG
                     
Both request timed out

Results:
ORFs found: 261 Genetic code: 1 Start codon: 'ATG' only
ORFs were calculated on the interval from 1 to 50000 nt

Sample ORF (ORF52):
>lcl|ORF52
MSFGLTNAPTAFMDLMNRVFKDFLDNFVIVFIDDILVYSRSEAEHEQHLR
MVLQRLRDHKLYAKFKKCEFWLSQVSFLGHIVGKDGIMVDPGKIEAVKNW
PRPKTVTEIRSFLGLAGYYRRFVEGFSKIAMPLSELTRKNQRFIWSDKCE
KSFQELKQRLIIAPVLALPSDQEKFVVYCDASRQGLGCVLMQADKVVAYA
SRQLKDYEQRYPTHDLELAAVVFALKIWRHYLYGEKCEIYTDHKSLKYFF
TQKDLNMRQRRWLELVKDYDCEILYHPGKANVVADALSRKGPDQIANMVM
ISSQLASEMTRANIELVTEKLFNLTLQSDLLERVRMAQLEDSELTKIRED
VLAGKAKDFSISDNGMMLFKARVCVPDFSELKKEILEEAHTTPYSLHPGT
TKMYQDLKPYFWWYGMKRDVVDYVTKCLTCQQIKAEHQRPAGLLQPLTLP
EWKWEDIAMDFVVGLPRTTGMYDSVWVVVDRFTKSAHFLPVKVTYTVDQY
ADLYVKEIVRLHGVPKSIVSDRDPKFTSKFWVSLQKAMGTNLKFSTTFHP
QTDGQSERTIQILEDLLRACVMDFGGSWNKYLPLIEFSYNNSYQSTIGMA
PYELLYGRKCRSPIHWDETGERKYLGPELVQKTNEAIDKIKARMLASQSR
QKSYADPKRRDVIFQPGDHVFL

Failed at Blast

SRX16875476

